<nav>

    <div class="nav-wrapper breadcrumb" style="padding-right: 25px; padding-left: 25px;">

        <div class="col s12">
            <a href="<?php echo APP_URL."transacciones/"; ?>" class="breadcrumb">Lista de transacciones</a>
            <a href="<?php echo APP_URL."transacciones/editar"; ?>" class="breadcrumb">Editar</a>
        </div>
        
    </div>

</nav>

<div class="row">

	<div class="col-sm-12">

		<h3>Editar transacción</h3>

        <hr>

		<br>

        <div class="row">

            <form action="<?php echo APP_URL."transacciones/editar"; ?>" method="POST">

                <input type="hidden" name="id" class="form-control" value="<?php echo $this->transacciones["id"]; ?>">

                <div class="input-field col s12">

                    <select name="account_id" class="form-control" required>

                        <?php foreach ($this->cuentas as $cuenta) {

                            if ($this->transacciones["account_id"]==$cuenta["id"]) { ?>

                            <option selected value="<?php echo $cuenta["id"]; ?>"><?php echo $cuenta["name"]; ?></option>

                        <?php }else{ ?>

                            <option value="<?php echo $cuenta["id"]; ?>"><?php echo $cuenta["name"]; ?></option>

                        <?php } } ?>

                    </select>

                     <label>Cuenta</label>

                </div>

                <div class="input-field col s12">

                    <select name="category_id" class="form-control" required>

                        <?php foreach ($this->categorias as $categoria) {

                            if ($this->transacciones["category_id"]==$categoria["id"]) {?>

                            <option selected value="<?php echo $categoria["id"]; ?>"><?php echo $categoria["name"]; ?></option>

                        <?php }else{ ?>

                            <option value="<?php echo $categoria["id"]; ?>"><?php echo $categoria["name"]; ?></option>

                        <?php } } ?>

                    </select>

                    <label>Categoria</label>

                </div>

                <div class="input-field col s12">

                    <input name="description" id="descripcion" type="text" class="form-control" value="<?php echo $this->transacciones["description"]; ?>" required>
                    <label for="descripcion">Descripción</label>

                </div>

                <div class="input-field col s12">

                    <label for="fecha">Fecha</label>
                    <input type="date" name="date" class="form-control" value="<?php echo $this->transacciones["date"]; ?>" required>

                </div>

                <div class="input-field col s12">

                    <input type="number" name="amount" step="0.01" class="form-control" value="<?php echo $this->transacciones["amount"]; ?>" required>
                    <label>Cantidad</label>

                </div>

                <input type="submit" class="btn btn-primary" value="Guardar transacción" style="background-color: #0069D9;">

            </form>

        </div>

    </div>

<div>