<nav>

    <div class="nav-wrapper breadcrumb" style="padding-right: 25px; padding-left: 25px;">

        <div class="col s12">
            <a href="<?php echo APP_URL."transacciones/"; ?>" class="breadcrumb">Lista de transacciones</a>
            <a href="<?php echo APP_URL."categorias/"; ?>" class="breadcrumb">Ver categorías</a>
        </div>
        
    </div>

</nav>

<div class="row">

	<div class="col-sm-12">

		<h3>Lista de categorías</h3>

		<a class="waves-effect waves-light btn" style="background-color: #0069D9;" href="<?php echo APP_URL."categorias/agregar"; ?>">Agregar categoría</a>

        <br>
        <br>

        <hr>

		<div>

			<table class="striped responsive-table">

				<tr>
					<th>ID</th>
                    <th>Categoría</th>
                    <th>Acción</th>
				</tr>

				<?php foreach ($this->categorias as $categoria): ?>

                    <tr>

                        <td><?php echo $categoria["id"]; ?></td>
                        <td><?php echo $categoria["name"]; ?></td>
                        <td>
                        
                            <a href="<?php echo APP_URL."categorias/editar/".$categoria["id"]; ?>"><i class="waves-effect waves-light btn-small" style="background-color: #E2E6EA;">Editar</i></a>

							|

                            <a href="<?php echo APP_URL."categorias/eliminar/".$categoria["id"]; ?>"><button type="button" class="btn btn-secondary btn-small confirmation3" style="background-color: #C82333;">Eliminar</button></a>   
                        
                        </td>

                    </tr>

                <?php endforeach; ?>

			</table>

		</div>

        

    </div>

</div>